<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Embedding PHP in HTML</title>
</head>
<body>
    <h1>This is plain HTML</h1>
    <P>So is this</P>
    <p>This HTML, but the day is generated by PHP: <?php  echo date("l")  ;?>, </p>
</body>
</html>
